### ISSUE TITLE
Hunt for any buttons or links that don't work. Hunt for cruft.

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/ZbayMobile#115]
Before handing to kinga let's do a final hunt for any non-working buttons or links, or any cruft.

**Comment by vinkabuki** [comment]
I've went through every possible combinations in app, there is one thing that is not working but we are planning to restore it - notifications settings. After task with restoring notifications is merged, it will be checked and this task will be closed.

**Comment by holmesworcester** [comment]
Let's close now then, unless anyone else would like a bite.

**Comment by kingalg** [comment]
Dev-hunt was successful because so far all buttons are working for me. I'm closing this as button-check will be a part of standard manual check in all new versions.
