### ISSUE TITLE
Upgrade Tor service - handle running daemons

### ISSUE THREAD

**Issue by siepra** [ZbayApp/ZbayMobile#22]

**Comment by siepra** [comment]
**TODO:** Remove tor-control module from project

**Comment by holmesworcester** [comment]
@siepra is this still a thing we have to do?

**Comment by siepra** [comment]
It's not necessary or urgent but I think it can stay there until we find
some time for it. Currently our Tor service for Android is working stable
and it fits our needs but it can be improved in the matter of managing
running processes (e.g. in case when there is already running Tor instance
on the device)

śr., 21 lip 2021, 16:50 użytkownik holmesworcester ***@***.***>
napisał:

**Comment by holmesworcester** [comment]
what happens when there’s an existing instance? anything bad?

**Comment by siepra** [comment]
The app will not start but it is rather hard to get to that situation -
nevertheless it is not impossible and that's why I kept this task.

In fact there is more work to do around Tor in Zbay mobile. We should
secure control port with cookie and do some research about bridges and
snowflake - yet it is not required for the app to run properly at this point

pt., 23 lip 2021, 22:34 użytkownik holmesworcester ***@***.***>
napisał:

> what happens when there’s an existing instance? anything bad?
>

**Comment by holmesworcester** [comment]
We can put off research on bridges and snowflake for now, as anti-censorship isn’t a focus yet—just security and privacy.

I just created an issue for securing the Tor control port: https://github.com/ZbayApp/ZbayMobile/issues/95

Have issues been created for any other security / privacy tasks?

**Comment by siepra** [comment]
This ticket is no longer accurate as controlling Tor over it's control port was moved from native services to waggle
