### ISSUE TITLE
Test application for running after internet connection lost

### ISSUE THREAD

**Issue by siepra** [ZbayApp/ZbayMobile#30]

**Comment by holmesworcester** [comment]
@siepra progress on this?

**Comment by siepra** [comment]
This should work without any additional work put in that matter. I want to test it but for now I'm blocked by waggle

**Comment by siepra** [comment]
Is blocked by https://github.com/ZbayApp/waggle/issues/63

**Comment by holmesworcester** [comment]
Can you explain the relationship between these two issues a bit more? I
don't get why one is a blocker for the other.

**Comment by siepra** [comment]
It's hard to check whether the messages are being saved to the store properly (after reconnecting to the web) if we can't see them in the correct order

**Comment by siepra** [comment]
On internet connection lost, the app behavior does not change at all. After reconnecting, user has to wait for messages to be replicated but it is not related to any internet connection state change
