### ISSUE TITLE
Layout bug in text entry field on Pixel 3

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/ZbayMobile#91]
![image](https://user-images.githubusercontent.com/213678/126508910-3f40c3f4-181c-4ed4-b8fc-6032c8fa3338.png)

The send button should be placed at the right side of the text field I think.

**Comment by siepra** [comment]
The blank space on the right side of the button is reserved for emojis, taking photos, uploading files etc. The design of the app is at very early step and the wireframes are not ready yet. Because of that some UI elements may seem buggy or incomplete
